import localFont from "next/font/local";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const alpino = localFont({
  src: [
    {
      path: "../public/fonts/Alpino-Variable.woff2",
      weight: "100 900",
      style: "normal",
    },
    {
      path: "../public/fonts/Alpino-Variable.woff",
      weight: "100 900",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-alpino",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${alpino.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
          <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
